### ISSUE TITLE
При указании накопительной ставки равной нулю выводится исключение

### ISSUE THREAD

**Issue by TinitaQA** [TinitaQA/javaqa-team-diplom-2#3]
# Описание
При указании накопительной ставки равной нулю выводится исключение IllegalArgumentException "Накопительная ставка не может быть отрицательной, а у вас: 0"

# Локация дефекта
https://github.com/TinitaQA/javaqa-team-diplom-2/blob/b85e536e3187601c8402880a4df7a4723d768038/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TinitaQA/javaqa-team-diplom-2/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. В тестируемом классе CreditAccountTest создать объект CreditAccount со значениями initialBalance 1_000, creditLimit 5_000, rate 0
3. Запустить программу
4. Посмотреть на вывод в консоли

*Ожидаемый результат* Накопительная ставка равна нулю

*Фактический результат* Выводится исключение IllegalArgumentException "Накопительная ставка не может быть отрицательной, а у вас: 0"

# Тест
https://github.com/TinitaQA/javaqa-team-diplom-2/blob/b85e536e3187601c8402880a4df7a4723d768038/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L10

# Скриншот
![image](https://github.com/TinitaQA/javaqa-team-diplom-2/assets/144548911/fe6373e1-6d1f-4896-988a-bed0e176f905)

# Окружение
* **Операционная система:** macOS 12.7.1
* **IDE:** IntelliJ IDEA 2023.2.3 (Community Edition)
* **Java:** OpenJDK 11

@Mifalem

**Comment by Mifalem** [comment]
Вывод исключения осуществлялся когда rate <= 0, сейчас же исключение выводится когда rate < 0.
